services:
  postgres:
    image: postgres:17.4-bookworm
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: concurrentReadTable
    ports:
      - "5432:5432"

  app1:
    build: .
    image: concurrent-read-table
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres

  app2:
    build: .
    image: concurrent-read-table
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres